---
- name: Create web directory
  file:
    path: "~/backend-app"
    state: directory


- name: Extract zipped artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: Install npm dependencies
  shell: |
    cd ~/backend-app
    npm i


# - name: "install dependencies."
#   become: yes
#   apt:
#     name: "nodejs"
#     state: latest
#     update_cache: yes

# - name: "install pm2"
#   become: yes
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present


- name: Start app with pm2
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

- name: "Configuring pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
